version: '3'

services:
  web:
    container_name: svelte_container
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "3000:3000"
      - "9005:9005"
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    command: npm run dev --host

volumes:
  node_modules: